// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTq0K-En9axVSrMXGLsKXmKdkxrencYoM',
    appId: '1:371052104121:web:e11fd8c7ed49e75a4b4e68',
    messagingSenderId: '371052104121',
    projectId: 'campus-recruitment-d21b3',
    authDomain: 'campus-recruitment-d21b3.firebaseapp.com',
    storageBucket: 'campus-recruitment-d21b3.appspot.com',
    measurementId: 'G-DYFTNFLK5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeeYlfM_0osAGo6ycDDWPlXkcailbf0lo',
    appId: '1:371052104121:android:afc79f1324b38b454b4e68',
    messagingSenderId: '371052104121',
    projectId: 'campus-recruitment-d21b3',
    storageBucket: 'campus-recruitment-d21b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0P2DHVDtEr38A8iQAzSQQzWjgHxXj35s',
    appId: '1:371052104121:ios:5e076631cad8cc0d4b4e68',
    messagingSenderId: '371052104121',
    projectId: 'campus-recruitment-d21b3',
    storageBucket: 'campus-recruitment-d21b3.appspot.com',
    iosBundleId: 'com.example.campusRecruitment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0P2DHVDtEr38A8iQAzSQQzWjgHxXj35s',
    appId: '1:371052104121:ios:074e03903f6795fa4b4e68',
    messagingSenderId: '371052104121',
    projectId: 'campus-recruitment-d21b3',
    storageBucket: 'campus-recruitment-d21b3.appspot.com',
    iosBundleId: 'com.example.campusRecruitment.RunnerTests',
  );
}
